# Generated by Django 5.0.2 on 2024-02-12 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LFTplatform", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activityday",
            name="day_of_week",
            field=models.CharField(
                choices=[
                    ("mon", "Monday"),
                    ("tue", "Tuesday"),
                    ("wed", "Wednesday"),
                    ("thu", "Thursday"),
                    ("fri", "Friday"),
                    ("sat", "Saturday"),
                    ("sun", "Sunday"),
                ],
                max_length=3,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="recruit",
            name="activity_days_recruit",
            field=models.ManyToManyField(
                blank=True, related_name="active_recruits", to="LFTplatform.activityday"
            ),
        ),
    ]
