# Generated by Django 4.1 on 2024-04-20 10:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("LFTplatform", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="global_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="role",
        ),
        migrations.AddField(
            model_name="user",
            name="public_server_name",
            field=models.CharField(default="ADMIN_DEFAULT_PUBLIC_NAME", max_length=32),
        ),
        migrations.AddField(
            model_name="user",
            name="recruiter_role",
            field=models.BooleanField(default=False),
        ),
    ]
