# Generated by Django 4.1 on 2024-02-26 20:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("LFTplatform", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="in_search_for_a",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="looking_for",
                to="LFTplatform.charactercharacteristics",
            ),
        ),
    ]
