# Generated by Django 5.0.2 on 2024-02-14 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LFTplatform", "0003_alter_guild_options_alter_character_wcl_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recruit",
            name="activity_days_recruit",
            field=models.ManyToManyField(
                blank=True, related_name="recruits", to="LFTplatform.activityday"
            ),
        ),
    ]
