# Generated by Django 4.1 on 2024-02-26 20:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("LFTplatform", "0003_alter_team_guild_alter_team_loot_system_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="team_progress",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
