# Generated by Django 5.0.2 on 2024-02-19 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LFTplatform", "0004_alter_recruit_activity_days_recruit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recruit",
            name="activity_time_end",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="recruit",
            name="activity_time_start",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="recruit",
            name="note",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
