# Generated by Django 4.1 on 2024-02-26 20:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("LFTplatform", "0004_alter_team_team_progress"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="activity_time_end",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="team",
            name="activity_time_start",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
