# Generated by Django 4.1 on 2024-02-21 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("LFTplatform", "0005_alter_recruit_activity_time_end_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recruit",
            name="discord",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="recruit",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="character",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="character",
                to="LFTplatform.recruit",
            ),
        ),
    ]
