# Generated by Django 4.1 on 2024-02-26 21:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("LFTplatform", "0005_alter_team_activity_time_end_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="in_search_for_a",
        ),
        migrations.AddField(
            model_name="team",
            name="looking_for",
            field=models.ManyToManyField(
                blank=True,
                related_name="teams_looking_for",
                to="LFTplatform.charactercharacteristics",
            ),
        ),
    ]
