# Generated by Django 5.0.2 on 2024-02-12 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LFTplatform", "0006_team_team_unique_team_name_for_each_guild"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="activity_days",
        ),
        migrations.RemoveField(
            model_name="recruit",
            name="activity_days",
        ),
        migrations.AddField(
            model_name="recruit",
            name="activity_days_recruit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("mon", "Monday"),
                    ("tue", "Tuesday"),
                    ("wed", "Wednesday"),
                    ("thu", "Thursday"),
                    ("fri", "Friday"),
                    ("sat", "Saturday"),
                    ("sun", "Sunday"),
                ],
                max_length=3,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="activity_days_team",
            field=models.CharField(
                blank=True,
                choices=[
                    ("mon", "Monday"),
                    ("tue", "Tuesday"),
                    ("wed", "Wednesday"),
                    ("thu", "Thursday"),
                    ("fri", "Friday"),
                    ("sat", "Saturday"),
                    ("sun", "Sunday"),
                ],
                max_length=3,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="guild",
            name="faction",
            field=models.CharField(
                choices=[("alliance", "Alliance"), ("horde", "Horde")], max_length=8
            ),
        ),
        migrations.DeleteModel(
            name="ActivityDay",
        ),
    ]
