# Generated by Django 4.1 on 2024-03-06 07:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("LFTplatform", "0006_remove_team_in_search_for_a_team_looking_for"),
    ]

    operations = [
        migrations.AddField(
            model_name="guild",
            name="discord_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="guild",
            name="apply_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="guild",
            name="wcl_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
