# Generated by Django 5.0.2 on 2024-02-12 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LFTplatform", "0007_remove_team_activity_days_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="activity_days_team",
            field=models.CharField(
                blank=True,
                choices=[
                    ("mon", "Monday"),
                    ("tue", "Tuesday"),
                    ("wed", "Wednesday"),
                    ("thu", "Thursday"),
                    ("fri", "Friday"),
                    ("sat", "Saturday"),
                    ("sun", "Sunday"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="team",
            constraint=models.UniqueConstraint(
                fields=("name", "guild", "activity_days_team"),
                name="unique_activity_time_for_each_team_and_guild",
            ),
        ),
    ]
