# Generated by Django 4.1 on 2024-03-11 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("LFTplatform", "0007_guild_discord_link_alter_guild_apply_link_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivitySession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time_start", models.TimeField()),
                ("time_end", models.TimeField()),
                (
                    "day",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="LFTplatform.activityday",
                        verbose_name="day_of_week",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="team",
            name="activity_sessions",
            field=models.ManyToManyField(to="LFTplatform.activitysession"),
        ),
    ]
