# Generated by Django 5.0.2 on 2024-02-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LFTplatform", "0008_alter_team_activity_days_team_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.CharField(
                        choices=[
                            ("mon", "Monday"),
                            ("tue", "Tuesday"),
                            ("wed", "Wednesday"),
                            ("thu", "Thursday"),
                            ("fri", "Friday"),
                            ("sat", "Saturday"),
                            ("sun", "Sunday"),
                        ],
                        max_length=3,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="recruit",
            name="activity_days_recruit",
        ),
        migrations.RemoveField(
            model_name="team",
            name="activity_days_team",
        ),
        migrations.AddField(
            model_name="recruit",
            name="activity_days_recruit",
            field=models.ManyToManyField(to="LFTplatform.activityday"),
        ),
        migrations.AddField(
            model_name="team",
            name="activity_days_team",
            field=models.ManyToManyField(to="LFTplatform.activityday"),
        ),
    ]
