# Generated by Django 5.0.2 on 2024-02-12 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "LFTplatform",
            "0009_activityday_remove_recruit_activity_days_recruit_and_more",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="team",
            name="unique_activity_time_for_each_team_and_guild",
        ),
    ]
