# Generated by Django 4.1 on 2024-03-11 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("LFTplatform", "0009_remove_team_activity_time_end_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="activity_days_team",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="active_teams",
                to="LFTplatform.activityday",
            ),
        ),
    ]
