# Generated by Django 4.1 on 2024-03-11 17:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("LFTplatform", "0010_alter_team_activity_days_team"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="activity_days_team",
        ),
    ]
