# Generated by Django 5.0.2 on 2024-02-12 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "LFTplatform",
            "0010_remove_team_unique_activity_time_for_each_team_and_guild",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="team",
            name="unique_team_name_for_each_guild",
        ),
    ]
