# Generated by Django 5.0.2 on 2024-02-12 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LFTplatform", "0011_remove_team_unique_team_name_for_each_guild"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="activity_days_team",
        ),
        migrations.AddConstraint(
            model_name="team",
            constraint=models.UniqueConstraint(
                fields=("name", "guild"), name="unique_team_name_for_each_guild"
            ),
        ),
    ]
