# Generated by Django 5.0.2 on 2024-02-12 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("LFTplatform", "0012_remove_team_activity_days_team_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Team",
        ),
    ]
