# Generated by Django 4.1 on 2024-03-19 08:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("LFTplatform", "0013_alter_charactercharacteristics_spec_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="charactercharacteristics",
            options={
                "ordering": ["class_name", "spec_name"],
                "verbose_name_plural": "Class-spec combinations",
            },
        ),
        migrations.AlterField(
            model_name="charactercharacteristics",
            name="spec_name",
            field=models.CharField(
                blank=True,
                choices=[
                    ("blood", "Blood"),
                    ("frost", "Frost"),
                    ("unholy", "Unholy"),
                    ("balance", "Balance"),
                    ("feral_dps", "Feral dps"),
                    ("feral_tank", "Feral tank"),
                    ("restoration", "Restoration"),
                    ("beast_mastery", "Beast mastery"),
                    ("marksmanship", "Marksmanship"),
                    ("survival", "Survival"),
                    ("arcane", "Arcane"),
                    ("fire", "Fire"),
                    ("holy", "Holy"),
                    ("protection", "Protection"),
                    ("retribution", "Retribution"),
                    ("discipline", "Discipline"),
                    ("shadow", "Shadow"),
                    ("assassination", "Assassination"),
                    ("combat", "Combat"),
                    ("subtlety", "Subtlety"),
                    ("elemental", "Elemental"),
                    ("enhancement", "Enhancement"),
                    ("affliction", "Affliction"),
                    ("demonology", "Demonology"),
                    ("destruction", "Destruction"),
                    ("arms", "Arms"),
                    ("fury", "Fury"),
                ],
                default="spec_name",
                max_length=16,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="charactercharacteristics",
            constraint=models.UniqueConstraint(
                fields=("class_name", "spec_name"), name="unique_class_spec_combination"
            ),
        ),
    ]
