# Generated by Django 5.0.2 on 2024-02-12 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LFTplatform", "0013_delete_team"),
    ]

    operations = [
        migrations.RenameField(
            model_name="guild",
            old_name="name",
            new_name="guild_name",
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team_name", models.CharField(max_length=24)),
                ("loot_system", models.CharField(default="Undefined", max_length=16)),
                ("team_size", models.IntegerField()),
                ("team_progress", models.IntegerField(default=0)),
                ("activity_time_start", models.TimeField()),
                ("activity_time_end", models.TimeField()),
                (
                    "activity_days_team",
                    models.ManyToManyField(to="LFTplatform.activityday"),
                ),
                (
                    "guild",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guild",
                        to="LFTplatform.guild",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "teams",
            },
        ),
        migrations.AddConstraint(
            model_name="team",
            constraint=models.UniqueConstraint(
                fields=("team_name", "guild"), name="unique_team_name_for_each_guild"
            ),
        ),
    ]
