# Generated by Django 4.1 on 2024-03-20 10:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("LFTplatform", "0014_alter_charactercharacteristics_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="guild",
            options={"ordering": ["guild_name"], "verbose_name_plural": "guilds"},
        ),
    ]
