# Generated by Django 5.0.2 on 2024-02-12 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("LFTplatform", "0014_rename_name_guild_guild_name_team_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="team",
            name="unique_team_name_for_each_guild",
        ),
    ]
