# Generated by Django 5.0.2 on 2024-02-12 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("LFTplatform", "0015_remove_team_unique_team_name_for_each_guild"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="activity_days_team",
        ),
        migrations.RemoveField(
            model_name="recruit",
            name="activity_days_recruit",
        ),
        migrations.RemoveField(
            model_name="character",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="guild",
            name="recruiter",
        ),
        migrations.RemoveField(
            model_name="team",
            name="guild",
        ),
        migrations.DeleteModel(
            name="ActivityDay",
        ),
        migrations.DeleteModel(
            name="Character",
        ),
        migrations.DeleteModel(
            name="Recruit",
        ),
        migrations.DeleteModel(
            name="Guild",
        ),
        migrations.DeleteModel(
            name="Team",
        ),
    ]
