# Generated by Django 4.1 on 2024-03-25 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("LFTplatform", "0016_alter_guild_faction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activityday",
            name="day_of_week",
            field=models.CharField(
                choices=[
                    ("Mon", "Mon"),
                    ("Tue", "Tue"),
                    ("Wed", "Wed"),
                    ("Thu", "Thu"),
                    ("Fri", "Fri"),
                    ("Sat", "Sat"),
                    ("Sun", "Sun"),
                ],
                max_length=3,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="guild",
            name="faction",
            field=models.CharField(
                choices=[("Any", "Any"), ("Alliance", "Alliance"), ("Horde", "Horde")],
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="activity_sessions",
            field=models.ManyToManyField(
                related_name="sessions", to="LFTplatform.activitysession"
            ),
        ),
    ]
