# Generated by Django 4.1 on 2024-03-27 19:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "LFTplatform",
            "0017_alter_activityday_day_of_week_alter_guild_faction_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="loot_system",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Any", "Any"),
                    ("EPGP", "EPGP"),
                    ("LC", "LC"),
                    ("SR", "SR"),
                    ("DKP", "DKP"),
                    ("GDKP", "GDKP"),
                    ("Other", "Other"),
                ],
                default="Undefined",
                max_length=16,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="team_size",
            field=models.IntegerField(
                blank=True, choices=[("25", "25"), ("10", "10")], null=True
            ),
        ),
    ]
